/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:916731a4-6e5c-4951-9d25-8ffa22c38abd",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_beDnF9BS6",
    "aws_user_pools_web_client_id": "m2bd3s6m6lel5qfvqqu70c8qh",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://q7c5zxuitnawfdo2c4icwddltu.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-m7pn7ypvvnbnnl5l4bg7gj4bta",
    "aws_user_files_s3_bucket": "amplifybucketexample220334-dev",
    "aws_user_files_s3_bucket_region": "us-east-1"
};


export default awsmobile;
